// <auto-generated />
using System;
using DNR26V2.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DNR26V2.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260417173216_Module3_ProductAttributeValue_IstVorlageV2")]
    partial class Module3_ProductAttributeValue_IstVorlageV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DNR26V2.Domain.Entities.MasterData.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ALAdresse")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ALAdresse2")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ALInhaber")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ALLand")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ALName2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ALOrt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ALPLZ")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("AbweichendeLieferadresse")
                        .HasColumnType("bit");

                    b.Property<string>("Adresse")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Adresse2")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("Aktiv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("AusnahmeTurWertId")
                        .HasColumnType("int");

                    b.Property<string>("EMail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ErstelltAm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ErstelltVon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("GeaendertAm")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeaendertVon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Geraete1")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Geraete2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Geraete3")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Geraete4")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Geraete5")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Handynummer")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Inhaber")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("KundenGruppeWertId")
                        .HasColumnType("int");

                    b.Property<string>("Kundenname")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Kundennummer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Land")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("Deutschland");

                    b.Property<bool>("LiefertDi")
                        .HasColumnType("bit");

                    b.Property<bool>("LiefertDo")
                        .HasColumnType("bit");

                    b.Property<bool>("LiefertFr")
                        .HasColumnType("bit");

                    b.Property<bool>("LiefertMi")
                        .HasColumnType("bit");

                    b.Property<bool>("LiefertMo")
                        .HasColumnType("bit");

                    b.Property<bool>("LiefertSa")
                        .HasColumnType("bit");

                    b.Property<bool>("LiefertSo")
                        .HasColumnType("bit");

                    b.Property<decimal>("Limit")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Name2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notizen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Offen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Ort")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PLZ")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("PreisAusblenden")
                        .HasColumnType("bit");

                    b.Property<int?>("RouteId")
                        .HasColumnType("int");

                    b.Property<int>("Routenfolge")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Telefonnummer")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TurWertId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AusnahmeTurWertId");

                    b.HasIndex("KundenGruppeWertId");

                    b.HasIndex("Kundennummer")
                        .IsUnique();

                    b.HasIndex("RouteId");

                    b.HasIndex("TurWertId");

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("DNR26V2.Domain.Entities.MasterData.CustomerProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktiv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("ArtikelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ErstelltAm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ErstelltVon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("GeaendertAm")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeaendertVon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Gewicht")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)")
                        .HasDefaultValue(0m);

                    b.Property<int>("KundeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Menge")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("Preis")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.HasIndex("ArtikelId");

                    b.HasIndex("KundeId", "ArtikelId")
                        .IsUnique();

                    b.ToTable("CustomerProduct", (string)null);
                });

            modelBuilder.Entity("DNR26V2.Domain.Entities.MasterData.CustomerProductAttributeMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttributId")
                        .HasColumnType("int");

                    b.Property<int?>("AttributWertId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ErstelltAm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ErstelltVon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FreierText")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("GeaendertAm")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeaendertVon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AttributId");

                    b.HasIndex("AttributWertId");

                    b.HasIndex("CustomerProductId");

                    b.ToTable("CustomerProductAttributeMapping", (string)null);
                });

            modelBuilder.Entity("DNR26V2.Domain.Entities.MasterData.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktiv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("ErstelltAm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ErstelltVon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Fahrercode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("GeaendertAm")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeaendertVon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefonnummer")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Fahrercode")
                        .IsUnique();

                    b.ToTable("Driver", (string)null);
                });

            modelBuilder.Entity("DNR26V2.Domain.Entities.MasterData.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktiv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Artikelnummer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Bezeichnung2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("EKPreis")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Einheit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("STK");

                    b.Property<DateTime>("ErstelltAm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ErstelltVon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Feld1")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Feld2")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Feld3")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Feld4")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("GeaendertAm")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeaendertVon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("MwstProzent")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(7m);

                    b.Property<string>("Notizen")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Printfarbe")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("VKPreis")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.HasIndex("Artikelnummer")
                        .IsUnique();

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("DNR26V2.Domain.Entities.MasterData.ProductAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktiv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("EntityType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("ErstelltAm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ErstelltVon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Feldtyp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("GeaendertAm")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeaendertVon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaxLaenge")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProductAttribute", (string)null);
                });

            modelBuilder.Entity("DNR26V2.Domain.Entities.MasterData.ProductAttributeMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtikelId")
                        .HasColumnType("int");

                    b.Property<int>("AttributId")
                        .HasColumnType("int");

                    b.Property<int?>("AttributWertId")
                        .HasColumnType("int");

                    b.Property<string>("FreierText")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AttributId");

                    b.HasIndex("AttributWertId");

                    b.HasIndex("ArtikelId", "AttributId")
                        .IsUnique();

                    b.ToTable("ProductAttributeMapping", (string)null);
                });

            modelBuilder.Entity("DNR26V2.Domain.Entities.MasterData.ProductAttributeValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktiv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("AttributId")
                        .HasColumnType("int");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ErstelltAm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ErstelltVon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("GeaendertAm")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeaendertVon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IstVorlage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Sortierung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("AttributId");

                    b.ToTable("ProductAttributeValue", (string)null);
                });

            modelBuilder.Entity("DNR26V2.Domain.Entities.MasterData.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktiv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ErstelltAm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ErstelltVon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("GeaendertAm")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeaendertVon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IstWochenendtour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Routencode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Routencode")
                        .IsUnique();

                    b.ToTable("Route", (string)null);
                });

            modelBuilder.Entity("DNR26V2.Domain.Entities.System.AppSetup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("DruckerMitLogo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DruckerWeissesPapier")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ErstelltAm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ErstelltVon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirmenEmail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirmenLand")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("Deutschland");

                    b.Property<string>("FirmenOrt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirmenPLZ")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FirmenSteuernummer")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirmenTelefon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirmenUStIdNr")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Firmenadresse")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Firmenname")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("GeaendertAm")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeaendertVon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GutschriftPraefix")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("GS");

                    b.Property<string>("LieferscheinPraefix")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("LS");

                    b.Property<string>("RechnungPraefix")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("RE");

                    b.Property<int>("SeitenGroesse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(20);

                    b.Property<decimal>("StandardMwstProzent")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(7.00m);

                    b.Property<string>("StandardStandortCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ZahlungPraefix")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("ZA");

                    b.HasKey("Id");

                    b.ToTable("AppSetup", null, t =>
                        {
                            t.HasCheckConstraint("CK_AppSetup_Singleton", "[Id] = 1");
                        });
                });

            modelBuilder.Entity("DNR26V2.Domain.Entities.System.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Aktion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AlterWert")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Belegnummer")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Benutzer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DatensatzId")
                        .HasColumnType("int");

                    b.Property<string>("Grund")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IPAdresse")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NeuerWert")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tabellenname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Zeitstempel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Benutzer");

                    b.HasIndex("Tabellenname");

                    b.HasIndex("Zeitstempel");

                    b.ToTable("AuditLog", (string)null);
                });

            modelBuilder.Entity("DNR26V2.Domain.Entities.System.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Aktiv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ErstelltAm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ErstelltVon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("GeaendertAm")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeaendertVon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IstStandard")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Land")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("Deutschland");

                    b.Property<string>("Ort")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PLZ")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Standortcode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Standortcode")
                        .IsUnique();

                    b.ToTable("Location", (string)null);
                });

            modelBuilder.Entity("DNR26V2.Domain.Entities.System.NoSeries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktiv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Beschreibung")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ErstelltAm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ErstelltVon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("GeaendertAm")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeaendertVon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LetzteVerwendeteNr")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LetztesVerwendetesDatum")
                        .HasColumnType("date");

                    b.Property<string>("Nummernformat")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("000");

                    b.Property<string>("Praefix")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Seriencode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Trennzeichen")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nchar(1)")
                        .HasDefaultValue("-");

                    b.HasKey("Id");

                    b.HasIndex("Seriencode")
                        .IsUnique();

                    b.ToTable("NoSeries", (string)null);
                });

            modelBuilder.Entity("DNR26V2.Domain.Entities.System.UserGridSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Benutzername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Einstellungen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GeaendertAm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("GridKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Benutzername", "GridKey")
                        .IsUnique();

                    b.ToTable("UserGridSetting", (string)null);
                });

            modelBuilder.Entity("DNR26V2.Domain.Entities.MasterData.Customer", b =>
                {
                    b.HasOne("DNR26V2.Domain.Entities.MasterData.ProductAttributeValue", "AusnahmeTurWert")
                        .WithMany()
                        .HasForeignKey("AusnahmeTurWertId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DNR26V2.Domain.Entities.MasterData.ProductAttributeValue", "KundenGruppeWert")
                        .WithMany()
                        .HasForeignKey("KundenGruppeWertId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DNR26V2.Domain.Entities.MasterData.Route", null)
                        .WithMany("Kunden")
                        .HasForeignKey("RouteId");

                    b.HasOne("DNR26V2.Domain.Entities.MasterData.ProductAttributeValue", "TurWert")
                        .WithMany()
                        .HasForeignKey("TurWertId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AusnahmeTurWert");

                    b.Navigation("KundenGruppeWert");

                    b.Navigation("TurWert");
                });

            modelBuilder.Entity("DNR26V2.Domain.Entities.MasterData.CustomerProduct", b =>
                {
                    b.HasOne("DNR26V2.Domain.Entities.MasterData.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ArtikelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DNR26V2.Domain.Entities.MasterData.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("KundeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DNR26V2.Domain.Entities.MasterData.CustomerProductAttributeMapping", b =>
                {
                    b.HasOne("DNR26V2.Domain.Entities.MasterData.ProductAttribute", "Attribut")
                        .WithMany("KundenMappings")
                        .HasForeignKey("AttributId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DNR26V2.Domain.Entities.MasterData.ProductAttributeValue", "AttributWert")
                        .WithMany()
                        .HasForeignKey("AttributWertId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DNR26V2.Domain.Entities.MasterData.CustomerProduct", "CustomerProduct")
                        .WithMany("Spezifikationen")
                        .HasForeignKey("CustomerProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribut");

                    b.Navigation("AttributWert");

                    b.Navigation("CustomerProduct");
                });

            modelBuilder.Entity("DNR26V2.Domain.Entities.MasterData.ProductAttributeMapping", b =>
                {
                    b.HasOne("DNR26V2.Domain.Entities.MasterData.Product", "Artikel")
                        .WithMany()
                        .HasForeignKey("ArtikelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DNR26V2.Domain.Entities.MasterData.ProductAttribute", "Attribut")
                        .WithMany("Mappings")
                        .HasForeignKey("AttributId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DNR26V2.Domain.Entities.MasterData.ProductAttributeValue", "AttributWert")
                        .WithMany("Mappings")
                        .HasForeignKey("AttributWertId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Artikel");

                    b.Navigation("Attribut");

                    b.Navigation("AttributWert");
                });

            modelBuilder.Entity("DNR26V2.Domain.Entities.MasterData.ProductAttributeValue", b =>
                {
                    b.HasOne("DNR26V2.Domain.Entities.MasterData.ProductAttribute", "Attribut")
                        .WithMany("Werte")
                        .HasForeignKey("AttributId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribut");
                });

            modelBuilder.Entity("DNR26V2.Domain.Entities.MasterData.CustomerProduct", b =>
                {
                    b.Navigation("Spezifikationen");
                });

            modelBuilder.Entity("DNR26V2.Domain.Entities.MasterData.ProductAttribute", b =>
                {
                    b.Navigation("KundenMappings");

                    b.Navigation("Mappings");

                    b.Navigation("Werte");
                });

            modelBuilder.Entity("DNR26V2.Domain.Entities.MasterData.ProductAttributeValue", b =>
                {
                    b.Navigation("Mappings");
                });

            modelBuilder.Entity("DNR26V2.Domain.Entities.MasterData.Route", b =>
                {
                    b.Navigation("Kunden");
                });
#pragma warning restore 612, 618
        }
    }
}
